Filmers/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#home'
  resources :photos do
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resources :users, only: %i[show new create edit update destroy]
  get '/admin', to: 'users#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Filmers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Filmers/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

Filmers/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :photo
  belongs_to :user
  validates_uniqueness_of :photo_id, scope: :user_id
end

Filmers/app/models/photo.rb
class Photo < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { maximum: 20 }

  has_many_attached :images
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :likes_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
end

Filmers/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

Filmers/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true, length: { maximum: 16 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, length: { minimum: 8 }

  has_many :photos, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likes_photos, through: :likes, source: :photo
  has_many :comments, dependent: :destroy

  def already_liked?(photo)
    self.likes.exists?(photo_id: photo.id)
  end
end

Filmers/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @photo = Photo.find_by(params[:id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.photo_id = @photo.id
    if @comment.save
      redirect_to photo_path(@photo), notice: 'コメントを投稿しました'
    else
      render photo_path(@photo)
      flash[:notice] = 'コメントを投稿できませんでした'
    end
  end

  def destroy
    @comment = Comment.find_by(photo_id: params[:id], user_id: current_user.id)
    @comment.destroy
    redirect_to photo_path, notice: 'コメントを削除しました'
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

Filmers/app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :login_required
  
  def home
  end
end

Filmers/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(photo_id: params[:photo_id])
    flash[:notice] = "#{@like.photo.title}にLIKEをつけました！"
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(photo_id: params[:photo_id], user_id: current_user.id)
    @like.destroy
    flash[:notice] = "#{@like.photo.title}のLIKEを取り消しました"
    redirect_back(fallback_location: root_path)
  end
end

Filmers/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  skip_before_action :login_required, only: %i[index show]
  before_action :set_photo, only: %i[show edit update destroy]

  def index
    @photos = Photo.all.order(created_at: :desc)
  end

  def show
    @like = Like.new
    @comments = @photo.comments
    @comment = Comment.new
    @comment_find = Comment.find_by(user_id: current_user.id)
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = current_user.photos.new(photo_params)

    if @photo.save
      redirect_to photos_path, notice: '個展を開催しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @photo.update(photo_params)
      redirect_to photos_path, notice: '個展を編集しました'
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @photo.user_id
      @photo.destroy
      redirect_to photos_path, notice: "#{@photo.title}を削除しました"
    else
      redirect_to photos_path, notice: '権限がありません'
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :description, images: [])
  end

  def set_photo
    @photo = Photo.find(params[:id])
  end
end

Filmers/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :login_required, only: %i[index show]
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to posts_path, notice: '記事を投稿しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: '記事を編集しました'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "#{@post.title}を削除しました"
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :description)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

Filmers/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i[new index create]
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_admin, only: %i[index]

  def index
    @users = User.all.order(created_at: :desc)
  end

  def show
    redirect_to user_path(current_user), notice: '権限がありません' unless current_user.id == @user.id
    @photo = Photo.find_by(user_id: params[:id])

    @photos = current_user.photos
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to photos_path, notice: "#{@user.name}さん、Filmersへようこそ！"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to photos_path, notice: "#{@user.name}さんの情報を更新しました"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to photos_path, notice: "#{@user.name}さんのアカウントを削除しました"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def require_admin
    redirect_to root_url unless current_user.admin?
  end

  def set_user
    @user = User.find(params[:id])
  end
end

Filmers/app/helpers/application_helper.rb
module ApplicationHelper
end

Filmers/app/helpers/comments_helper.rb
module CommentsHelper
end

Filmers/app/helpers/home_helper.rb
module HomeHelper
end

Filmers/app/helpers/likes_helper.rb
module LikesHelper
end

Filmers/app/helpers/photos_helper.rb
module PhotosHelper
end

Filmers/app/helpers/posts_helper.rb
module PostsHelper
end

Filmers/app/helpers/sessions_helper.rb
module SessionsHelper
end

Filmers/app/helpers/users_helper.rb
module UsersHelper
end

Filmers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Filmers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="uk-navbar-container" uk-navbar>
        <div class="uk-navbar-left">
          <ul class="uk-navbar-nav">
            <li><a href="/" class="uk-margin-left">TOP</a></li>
            <li><%= link_to '個展一覧', photos_path %></li>
            <li><%= link_to '記事一覧', posts_path %></li>
          </ul>
        </div>
        <div class="uk-navbar-right">
          <ul class="uk-navbar-nav">
            <% if current_user %>
              <li>
                <%= link_to "#{current_user.name}さん", user_path(current_user), class: 'uk-margin-right' %>
                  <div class="uk-navbar-dropdown uk-padding-remove-bottom">
                    <ul class="uk-nav uk-navbar-dropdown-nav uk-align-center">
                      <li><%= link_to '個展を開催する', new_photo_path %></li>
                      <% if current_user.admin? %>
                        <li><%= link_to '記事を投稿する', new_post_path %></li>
                      <% end %>
                      <li><%= link_to 'マイページ', user_path(current_user) %></li>
                      <% if current_user.admin? %>
                        <li><%= link_to 'ユーザー', admin_path %></li>
                      <% end %>
                      <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
                    </ul>
                  </div>
              </li>
            <% else %>
              <li><%= link_to '新規登録', new_user_path %></li>
              <li><%= link_to 'ログイン', login_path, class: 'uk-margin-right' %></li>
            <% end %>
        </div>
      </nav>
    </header>

    <% if flash[:notice] %>
      <div class="uk-alert-primary uk-text-center"><%= flash[:notice] %></div>
    <% end %>

    <%= yield %>
  </body>
</html>