Filmers/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#home'
  resources :photos do
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resources :users, only: %i[show new create edit update destroy]
  get '/admin', to: 'users#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Filmers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Filmers/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

Filmers/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :photo
  belongs_to :user
  validates_uniqueness_of :photo_id, scope: :user_id
end

Filmers/app/models/photo.rb
class Photo < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { maximum: 20 }

  has_many_attached :images
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :likes_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
end

Filmers/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

Filmers/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true, length: { maximum: 16 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, length: { minimum: 8 }

  has_many :photos, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likes_photos, through: :likes, source: :photo
  has_many :comments, dependent: :destroy

  def already_liked?(photo)
    self.likes.exists?(photo_id: photo.id)
  end
end

Filmers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_url, notice: 'ログインが必要です' unless current_user
  end
end

Filmers/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @photo = Photo.find_by(params[:id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.photo_id = @photo.id
    if @comment.save
      redirect_to photo_path(@photo), notice: 'コメントを投稿しました'
    else
      render photo_path(@photo)
      flash[:notice] = 'コメントを投稿できませんでした'
    end
  end

  def destroy
    @comment = Comment.find_by(photo_id: params[:id], user_id: current_user.id)
    @comment.destroy
    redirect_to photo_path, notice: 'コメントを削除しました'
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

Filmers/app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :login_required
  
  def home
  end
end

Filmers/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(photo_id: params[:photo_id])
    flash[:notice] = "#{@like.photo.title}にLIKEをつけました！"
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(photo_id: params[:photo_id], user_id: current_user.id)
    @like.destroy
    flash[:notice] = "#{@like.photo.title}のLIKEを取り消しました"
    redirect_back(fallback_location: root_path)
  end
end

Filmers/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  skip_before_action :login_required, only: %i[index show]
  before_action :set_photo, only: %i[show edit update destroy]

  def index
    @photos = Photo.all.order(created_at: :desc)
  end

  def show
    @like = Like.new
    @comments = @photo.comments
    @comment = Comment.new
    @comment_find = Comment.find_by(user_id: current_user.id)
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = current_user.photos.new(photo_params)

    if @photo.save
      redirect_to photos_path, notice: '個展を開催しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @photo.update(photo_params)
      redirect_to photos_path, notice: '個展を編集しました'
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @photo.user_id
      @photo.destroy
      redirect_to photos_path, notice: "#{@photo.title}を削除しました"
    else
      redirect_to photos_path, notice: '権限がありません'
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :description, images: [])
  end

  def set_photo
    @photo = Photo.find(params[:id])
  end
end

Filmers/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :login_required, only: %i[index show]
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to posts_path, notice: '記事を投稿しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: '記事を編集しました'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "#{@post.title}を削除しました"
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :description)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

Filmers/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: session_params[:email])

    if @user&.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_to photos_path, notice: 'ログインしました'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'ログアウトしました'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

Filmers/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i[new index create]
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_admin, only: %i[index]

  def index
    @users = User.all.order(created_at: :desc)
  end

  def show
    redirect_to user_path(current_user), notice: '権限がありません' unless current_user.id == @user.id
    @photo = Photo.find_by(user_id: params[:id])

    @photos = current_user.photos
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to photos_path, notice: "#{@user.name}さん、Filmersへようこそ！"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to photos_path, notice: "#{@user.name}さんの情報を更新しました"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to photos_path, notice: "#{@user.name}さんのアカウントを削除しました"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def require_admin
    redirect_to root_url unless current_user.admin?
  end

  def set_user
    @user = User.find(params[:id])
  end
end

Filmers/app/helpers/application_helper.rb
module ApplicationHelper
end

Filmers/app/helpers/comments_helper.rb
module CommentsHelper
end

Filmers/app/helpers/home_helper.rb
module HomeHelper
end

Filmers/app/helpers/likes_helper.rb
module LikesHelper
end

Filmers/app/helpers/photos_helper.rb
module PhotosHelper
end

Filmers/app/helpers/posts_helper.rb
module PostsHelper
end

Filmers/app/helpers/sessions_helper.rb
module SessionsHelper
end

Filmers/app/helpers/users_helper.rb
module UsersHelper
end

Filmers/app/views/home/home.html.erb
<div class='uk-background-cover uk-light uk-background-fixed' data-src="<%= asset_path("IMG_8561.JPG") %>" uk-img>
  <h1 class='uk-heading-primary uk-text-center uk-animation-slide-top-medium title'>フィルム専用の写真投稿サイト | Filmers(フィルマーズ)</h1>
  <p class='uk-h5 uk-text-center uk-animation-slide-top-medium'>デジタルの時代にも色褪せぬフィルムカメラで、あなたの世界を表現しませんか。</p>
</div>

<div uk-grid style="width: 100%;">
  <div class="uk-width-1-2"><%= link_to '個展をみる', photos_path, class: 'uk-button uk-button-default uk-align-right uk-margin-top uk-text-bolder' %></div>
  <div class="uk-width-1-2"><a class="uk-button uk-button-default uk-margin-top uk-text-bolder" href="#target" uk-scroll>CONTACT US</a></div>
</div>

<div id="target" class="uk-container">
  <form>
    <fieldset class="uk-fieldset">

        <legend class="uk-legend uk-text-center">CONTACT US</legend>

        <div class="uk-margin">
          <input class="uk-input" type="text" placeholder="メールアドレス">
        </div>

        <div class="uk-margin">
          <textarea class="uk-textarea" rows="5" placeholder="お問い合わせ内容"></textarea>
        </div>

        <div class="uk-margin">
          <button class="uk-button uk-button-default uk-align-center">SEND YOUR CONTACT</button>
        </div>

    </fieldset>
  </form>
</div>

Filmers/app/views/photos/_form.html.erb
<% if photo.errors.present? %>
  <ul>
    <% photo.errors.full_messages.each do |message| %>
      <li class="uk-alert uk-alert-warning"><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="uk-container uk-margin-top">
  <%= form_with model: photo, local: true do |f| %>
    <fieldset class="uk-fieldset">

      <div class="uk-margin-medium-top">
          <%= f.label :title, class: 'uk-align-center uk-text-center' %>
          <%= f.text_field :title, required: 'required', class: 'uk-input uk-align-center uk-width-1-4' %>
      </div>

      <div class="uk-margin">
          <%= f.label :image, class: 'uk-align-center uk-text-center' %>
          <%= f.file_field :images, multiple: true, required: 'required', class: 'uk-align-center uk-width-1-6' %>
          <%= f.file_field :images, multiple: true, class: 'uk-align-center uk-width-1-6' %>
          <%= f.file_field :images, multiple: true, class: 'uk-align-center uk-width-1-6' %>
          <%= f.file_field :images, multiple: true, class: 'uk-align-center uk-width-1-6' %>
          <%= f.file_field :images, multiple: true, class: 'uk-align-center uk-width-1-6' %>
      </div>

      <div class="uk-margin">
          <%= f.label :description, class: 'uk-align-center uk-text-center' %>
          <%= f.text_area :description, rows: 10, class: 'uk-textarea uk-align-center uk-width-1-2', placeholder: '撮影機材、ロケーション、セッティング etc..' %>
      </div>

      <div class="uk-margin-medium">
          <%= f.submit '個展を開催する', class: 'uk-align-center uk-button uk-button-default' %>
      </div>

    </fieldset>
  <% end %>
</div>

Filmers/app/views/photos/edit.html.erb
<legend class="uk-legend uk-text-center uk-text-lead uk-margin-medium-top">個展を編集</legend>

<% if @photo.errors.present? %>
  <ul>
    <% @photo.errors.full_messages.each do |message| %>
      <li class="uk-alert uk-alert-warning"><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="uk-container uk-margin-top">
  <%= form_with model: @photo, local: true do |f| %>
    <fieldset class="uk-fieldset">

      <div class="uk-margin-medium-top">
        <%= f.label :title, class: 'uk-align-center uk-text-center' %>
        <%= f.text_field :title, required: 'required', class: 'uk-input uk-align-center uk-width-1-4' %>
      </div>

      <div class="uk-margin">
        <% @photo.images.each do |image| %>
          <%= image_tag image, class: 'uk-align-center uk-width-1-3' %>
        <% end %>
      </div>

      <div class="uk-margin">
        <%= f.label :description, class: 'uk-align-center uk-text-center' %>
        <%= f.text_area :description, rows: 10, class: 'uk-textarea uk-align-center uk-width-1-2 uk-height-small', placeholder: '撮影機材、ロケーション、セッティング etc..'  %>
      </div>

      <div class="uk-margin-medium">
        <%= f.submit '編集を完了する', class: 'uk-align-center uk-button uk-button-default' %>
      </div>

    </fieldset>
  <% end %>
</div>

Filmers/app/views/photos/index.html.erb
<div class="uk-container">
  <h1 class="uk-text-center uk-margin-top">Gallerys</h1>

  <% @photos.each do |photo| %>
    <div>
      <% if photo.images.attached?  %>
        <%= image_tag photo.images.first, class: 'uk-margin-top uk-width-1-2 uk-align-center' %>
      <% end %>
      <p class="uk-text-center"><%= link_to photo.title, photo_path(photo), class:'uk-link-heading uk-text-large' %></p>
      <p class="uk-text-center">Likes: <%= photo.likes_users.count %></p>
    </div>
  <% end %>

  <%= link_to '個展を開催する', new_photo_path, class: 'uk-button uk-button-default uk-align-center uk-text-center uk-width-1-6 uk-text-bolder uk-margin-medium-top uk-margin-large-bottom' %>
</div>

Filmers/app/views/photos/new.html.erb
<legend class="uk-legend uk-text-center uk-text-lead uk-margin-medium-top">新しく個展を開催する</legend>

<%= render partial: 'form', locals: { photo: @photo } %>

Filmers/app/views/photos/show.html.erb
<div class="uk-container">
  <h1 class="uk-text-center uk-margin-top"><%= "「#{@photo.title}」 by #{@photo.user.name}" %></h1>

  <div class="uk-position-relative uk-visible-toggle" tabindex="-1" uk-slideshow>

    <ul class="uk-slideshow-items">
      <% if @photo.images.attached? %>
        <% @photo.images.each do |image| %>
          <li>
            <%= image_tag image, target: '!.uk-slideshow-items' %>
          </li>
        <% end %>
      <% end %>
    </ul>

    <a class="uk-position-center-left uk-position-small uk-hidden-hover uk-text-lead" href="#" uk-slidenav-previous uk-slideshow-item="previous"></a>
    <a class="uk-position-center-right uk-position-small uk-hidden-hover uk-text-lead" href="#" uk-slidenav-next uk-slideshow-item="next"></a>

  </div>

  <p class="uk-text-center"><%= @photo.description %></p>
  <p class="uk-text-center"><%= @photo.created_at.strftime('%Y年 %m月 %d日') %></p>
  <p class="uk-text-center">LIKE: <%= @photo.likes.count %></p>

  <% if current_user %>
    <% if current_user.already_liked?(@photo) %>
      <%= button_to 'UNLIKE..', photo_like_path(@photo), method: :delete, class: 'uk-button uk-button-default uk-align-center' %>
    <% else %>
      <%= button_to 'LIKE!', photo_likes_path(@photo), class: 'uk-button uk-button-danger uk-align-center' %>
    <% end %>
  <% end %>

<% if @comment_find %>
  <table class="uk-table uk-table-divider">
    <thead>
        <tr>
            <th class="uk-align-center">Comments</th>
        </tr>
    </thead>
    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td class="uk-align-center uk-text-center"><%= "#{comment.content} by #{comment.user.name}" %></td>
          <% if comment.user_id == current_user.id %>
            <td>
              <%= link_to '削除', photo_comment_path(comment), method: :delete, class: 'uk-button uk-button-default uk-align-center uk-text-center uk-width-1-4' %>
            </td>
          <% else %>
            <td>
              <%= link_to '削除', photo_comment_path(comment), method: :delete, class: 'uk-button uk-button-default uk-align-center uk-text-center uk-width-1-5', style: 'display: none;' %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <table class="uk-table uk-table-divider">
    <thead>
        <tr>
            <th class="uk-align-center uk-text-center">Comments</th>
        </tr>
    </thead>
    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td class="uk-align-center uk-text-center"><%= "#{comment.content} by #{comment.user.name}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

  <div class="uk-margin">
    <%= form_for [@photo, @comment] do |f| %>
      <%= f.label :content, 'COMMENT', class: 'uk-align-center uk-text-center' %>
      <%= f.text_field :content, rows: 5, class: 'uk-textarea uk-width-1-2 uk-align-center' %>
      <%= f.submit '送信', class: 'uk-align-center uk-button uk-button-default' %>
    <% end %>
  </div>

  <% if current_user %>
    <% if current_user.id == @photo.user_id %>
      <%= link_to '編集', edit_photo_path(@photo), class: 'uk-align-right uk-link-text' %>
      <%= link_to '削除', photo_path(@photo), method: :delete, data: { confirm: "#{@photo.title}を削除します。本当によろしいですか？" }, class: 'uk-align-right uk-link-text' %>
    <% end %>
  <% end %>
</div>

Filmers/app/views/posts/_form.html.erb
<% if post.errors.present? %>
  <ul>
    <% post.errors.full_messages.each do |message| %>
      <li class="uk-alert uk-alert-warning"><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="uk-container uk-margin-top">
  <%= form_with model: post, local: true do |f| %>
    <fieldset class="uk-fieldset">

      <div class="uk-margin-medium-top">
          <%= f.label :title, 'タイトル', class: 'uk-align-center uk-text-center' %>
          <%= f.text_field :title, required: 'required', class: 'uk-input uk-align-center uk-width-1-2' %>
      </div>

      <div class="uk-margin">
        <%= f.label :description, '概要', class: 'uk-align-center uk-text-center' %>
        <%= f.text_area :description, rows: 5, required: 'required', class: 'uk-textarea uk-align-center uk-width-1-2' %>
      </div>

      <div class="uk-margin">
          <%= f.label :body, '本文', class: 'uk-align-center uk-text-center' %>
          <%= f.text_area :body, rows: 30, required: 'required', class: 'uk-textarea uk-align-center uk-width-1-2' %>
      </div>

      <div class="uk-margin-medium">
          <%= f.submit '投稿する', class: 'uk-align-center uk-button uk-button-default' %>
      </div>

    </fieldset>
  <% end %>
</div>

Filmers/app/views/posts/edit.html.erb
<legend class="uk-legend uk-text-center uk-text-lead uk-margin-medium-top">記事編集</legend>

<%= render partial: 'form', locals: { post: @post } %>

Filmers/app/views/posts/index.html.erb
<div class="uk-container uk-margin-top">
  <h1 class="uk-text-center">Articles</h1>

  <div class="uk-child-width-1-2@m uk-margin-medium-top" uk-grid>
    <% @posts.each do |post| %>
      <div>
          <div class="uk-card uk-card-default">
              <%# <div class="uk-card-media-top"> %>
                  <%# <% if @post.images.attached? %>
                    <%# <%= image_tag @photo.images.first %>
                  <%# <% end %>
              <%# </div> %>
              <div class="uk-card-body">
                  <h3 class="uk-card-title"><%= link_to post.title, post_path(post), class: 'uk-link-heading' %></h3>
                  <p><%= post.description %></p>
              </div>

              <div class="uk-card-footer">
                <%= link_to 'Read more', post_path(post), class: 'uk-button uk-button-text' %>
              </div>
          </div>
      </div>
    <% end %>

Filmers/app/views/posts/new.html.erb
<legend class="uk-legend uk-text-center uk-text-lead uk-margin-medium-top">新規記事作成</legend>

<%= render partial: 'form', locals: { post: @post } %>

Filmers/app/views/posts/show.html.erb
<div class="uk-container uk-width-1-2">
  <article class="uk-article">

      <h1 class="uk-article-title uk-text-center uk-margin-medium-top"><%= @post.title %></h1>

      <p class="uk-article-meta uk-text-center">Written by <%= @post.created_at.strftime('%Y-%m-%d') %></p>

      <p class="uk-align-center"><%= @post.body %></p>

      <%= link_to 'Read more articles', posts_path, class: 'uk-button uk-button-text uk-align-center uk-text-center uk-width-1-3' %>

  </article>

  <% if current_user %>
    <% if current_user.admin? %>
      <%= link_to '編集', edit_post_path(@post), class: 'uk-link-text uk-align-right' %>
      <%= link_to '削除', post_path(@post), method: :delete, data: { confirm: "#{@post.title}を削除します。本当によろしいですか？" }, class: 'uk-link-text uk-align-right' %>
    <% end %>  
  <% end %>
</div>

Filmers/app/views/users/_form.html.erb
<% if user.errors.present? %>
  <ul>
    <% user.errors.full_messages.each do |message| %>
      <li class="uk-alert uk-alert-warning"><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="uk-container uk-margin-top">
  <%= form_with model: user, local: true do |f| %>
    <fieldset class="uk-fieldset">

      <div class="uk-margin-medium-top">
          <%= f.label :name, class: 'uk-align-center uk-text-center' %>
          <%= f.text_field :name, required: 'required', class: 'uk-input uk-align-center uk-width-1-4' %>
      </div>

      <div class="uk-margin">
          <%= f.label :email, 'メールアドレス', class: 'uk-align-center uk-text-center' %>
          <%= f.text_field :email, required: 'required', class: 'uk-input uk-align-center uk-width-1-4' %>
      </div>

      <div class="uk-margin">
          <%= f.label :password, 'パスワード', class: 'uk-align-center uk-text-center' %>
          <%= f.password_field :password, required: 'required', class: 'uk-input uk-align-center uk-width-1-4' %>
      </div>

      <div class="uk-margin">
          <%= f.label :password_confirmation, class: 'uk-align-center uk-text-center' %>
          <%= f.password_field :password_confirmation, required: 'required', class: 'uk-input uk-align-center uk-width-1-4' %>
      </div>

      <div class="uk-margin-medium">
          <%= f.submit '登録', class: 'uk-align-center uk-button uk-button-default' %>
      </div>

    </fieldset>
  <% end %>
</div>

Filmers/app/views/users/edit.html.erb
<legend class="uk-legend uk-text-center uk-text-lead uk-margin-medium-top">ユーザー情報編集</legend>

<%= render partial: 'form', locals: { user: @user } %>

<%= link_to '退会する', user_path(@user), method: :delete, data: { confirm: "#{@user.name}さんのアカウントを削除します。本当によろしいですか？" }, class: 'uk-align-center' %>

Filmers/app/views/users/index.html.erb
<h1>ユーザー一覧（管理者のみ）</h1>

<% @users.each do |user| %>
<p>
<%= "ユーザー名: #{user.name}" %>
<%= "メールアドレス: #{user.email}" %>
<%= link_to '削除', user_path(user), method: :delete, data: { confirm: '本当によろしいですか？' } %>
</p>
<% end %>

Filmers/app/views/users/new.html.erb
<legend class="uk-legend uk-text-center uk-text-lead uk-margin-medium-top">新規登録</legend>

<%= render partial: 'form', locals: { user: @user } %>

Filmers/app/views/users/show.html.erb
<div class="uk-container">
  <h1 class="uk-text-center uk-margin-top"><%= "#{@user.name}'s Page" %></h1>

  <h2 class="uk-text-center">投稿一覧</h2>
    <% @user.photos.each do |photo| %>
      <h3 class="uk-text-center"><%= link_to photo.title, photo_path(photo), class: 'uk-link-heading' %></h3>
      <p class="uk-text-center uk-margin-remove-top"><%= image_tag photo.images.first, class: 'uk-width-1-2 uk-padding-remove-top' if photo.images.attached? %></p>
      <%= link_to "「#{photo.title}」の詳細をみる", photo_path(photo), class: 'uk-align-center uk-text-center uk-button uk-button-text uk-width-1-4' %>
    <% end %>

  <h2 class="uk-text-center">いいねした投稿</h2>
    <% @user.likes_photos.each do |photo| %>
      <h3 class="uk-text-center"><%= link_to photo.title, photo_path(photo), class: 'uk-link-heading' %></h3>
      <p class="uk-text-center uk-margin-remove-top"><%= image_tag photo.images.first, class: 'uk-width-1-2 uk-padding-remove-top' if photo.images.attached? %></p>
      <%= link_to "「#{photo.title}」の詳細をみる", photo_path(photo), class: 'uk-align-center uk-text-center uk-button uk-button-text uk-width-1-4' %>
    <% end %>

  <%= link_to '編集する', edit_user_path(@user), class: 'uk-link-text uk-align-right' %>
  <%= link_to '退会する', user_path(@user), method: :delete, data: { confirm: "#{@user.name}さんのアカウントを削除します。本当によろしいですか？" }, class: 'uk-link-text uk-align-right' %>
</div>